BaiTapLonNhom8/BaiTapLonNhom8/urls.py
from django.contrib import admin
from django.urls import path
from home import views as home
from login import views as login
from register import views as register
from contact import views as contact
from blog import views as blog
from my_profile import views as myProfile
from django.conf.urls.static import static
from django.conf import settings
from blogapp import views as blogapp
from loading import views as loading
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',loading.get_loading, name='loading'),
    path('home/',home.get_home, name='home'),
    path('login/',login.get_login, name='login'),
    path('logout/', login.logout_view, name='logout'),
    path('login/authenticate/', login.authenticate_user, name='authenticate_user'),
    path('register/',register.get_register, name='register'),
    path('contact/',contact.get_contact, name='contact'),
    path('blog/',blog.get_blog, name='blog'),
    path('blog/create/', blog.create_blog, name='create_blog'),
    path('blog/<int:blog_id>/', blog.blog_detail, name='blog_detail'),
    path('edit/<int:blog_id>/', blog.edit_blog, name='edit_blog'),
    path('delete/<int:blog_id>/', blog.delete_blog, name='delete_blog'),
    path('blog/<int:blog_id>/add_comment/', blog.add_comment, name='add_comment'),
    path('profile/', myProfile.user_profile, name='profile'),
    path('blogapp/', blogapp.get_blogapp, name='blog_app'),
    path('accounts/', include('allauth.urls')),
    path('login_with_facebook/', login.login_with_facebook, name='login_with_facebook'),
    path('facebook/', login.get_facebook, name='facebook'),
]+ static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

BaiTapLonNhom8/blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Model bài viết
class Blog(models.Model):
    id = models.AutoField(primary_key=True)  
    title = models.CharField(max_length=255)  
    thumnail = models.ImageField(upload_to='images', null=True, blank=True, default='default-avatar.jpg') 
    detail = models.CharField(max_length=2550)
    user = models.ForeignKey(User, on_delete=models.CASCADE)  # Liên kết với model người dùng

    def __str__(self):
        return self.title

# Model bình luận
class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.user.username} - {self.created_at}"

BaiTapLonNhom8/contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    contact_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    phone = models.CharField(max_length=20)
    email = models.EmailField()
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

BaiTapLonNhom8/blog/forms.py
from django import forms
from .models import Blog

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'thumnail', 'detail']
        widgets = {
            'detail': forms.Textarea(attrs={'rows': 10}),  
        }

BaiTapLonNhom8/contact/forms.py
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['name', 'phone', 'email', 'message']

BaiTapLonNhom8/blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required  
from .models import Blog
from .forms import BlogForm
from .comment_forms import CommentForm
from django.contrib import messages

def get_blog(request):
    query = request.GET.get('q')
    if query:
        # Tìm kiếm các bài viết có tiêu đề chứa từ khóa tìm kiếm
        blogs = Blog.objects.filter(title__icontains=query)
    else:
        blogs = Blog.objects.all()

    return render(request, 'blog.html', {'blogs': blogs, 'query': query}) 

@login_required(login_url='login') 
def create_blog(request):
    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES)
        if form.is_valid():
            # Lưu bài viết mới với thông tin của người dùng đăng nhập
            blog = form.save(commit=False)
            blog.user = request.user  # Gán người dùng hiện tại là người tạo bài viết
            blog.save()
            return redirect('blog_detail', blog_id=blog.id)
    else:
        form = BlogForm()
    return render(request, 'create_blog.html', {'form': form})

def blog_detail(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)
    comment_form = CommentForm()

    return render(request, 'blog_detail.html', {'blog': blog, 'comment_form': comment_form})

def add_comment(request, blog_id):
    blog = get_object_or_404(Blog, id=blog_id)

    if request.method == 'POST':
        if request.user.is_authenticated:
            comment_form = CommentForm(request.POST)
            if comment_form.is_valid():
                comment = comment_form.save(commit=False)
                comment.user = request.user
                comment.blog = blog
                comment.save()
                messages.success(request, 'Bình luận của bạn đã được thêm.')
            else:
                messages.error(request, 'Có lỗi xảy ra khi thêm bình luận.')
        else:
            # Chuyển hướng đến trang đăng nhập
            return redirect('login')

    # Chuyển hướng trở lại trang chi tiết blog sau khi thêm bình luận
    return redirect('blog_detail', blog_id=blog_id)

@login_required(login_url='login') 
def edit_blog(request, blog_id):
    # Lấy bài viết cần chỉnh sửa từ ID
    blog = get_object_or_404(Blog, id=blog_id, user=request.user)

    if request.method == 'POST':
        form = BlogForm(request.POST, request.FILES, instance=blog)
        if form.is_valid():
            form.save()
            return redirect('profile')
    else:
        form = BlogForm(instance=blog)
    
    return render(request, 'edit_blog.html', {'form': form})

@login_required(login_url='login') 
def delete_blog(request, blog_id):
    # Lấy bài viết cần xóa từ ID
    blog = get_object_or_404(Blog, id=blog_id, user=request.user)
    
    if request.method == 'POST':
        blog.delete()
        return redirect('profile')

    return render(request, 'confirm_delete_blog.html', {'blog': blog})

BaiTapLonNhom8/blogapp/views.py
from django.shortcuts import render

# Create your views here.
def get_blogapp(request):
    return render(request,'blogapp.html') 

BaiTapLonNhom8/contact/views.py
from django.shortcuts import render
from .forms import ContactForm

def get_contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form.save()
            message = "Phản hồi của bạn đã được gửi thành công!"
        else:
            message = "Đã có lỗi xảy ra. Vui lòng kiểm tra lại thông tin và thử lại."
    else:
        form = ContactForm()
        message = None
    return render(request, 'contact.html', {'form': form, 'message': message})

BaiTapLonNhom8/loading/views.py
from django.shortcuts import render

def get_loading(request):
    return render(request,'loading.html') 

BaiTapLonNhom8/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from allauth.socialaccount.models import SocialAccount

def get_login(request):
    # Hiển thị trang đăng nhập
    return render(request, 'login.html')

def authenticate_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('home')  # Chuyển hướng đến trang chính sau khi đăng nhập thành công
        else:
            return render(request, 'login.html', {'error': 'Tên đăng nhập hoặc mật khẩu không đúng'})
    else:
        return redirect('login')  # Nếu là request GET, chuyển hướng lại đến trang đăng nhập
        
def logout_view(request):
    # Đăng xuất người dùng
    logout(request)
    return redirect('login')

def get_facebook(request):
    return render(request,'facebookLogin.html') 

def login_with_facebook(request):
    # Chuyển hướng đến trang đăng nhập bằng Facebook của django-allauth
    return redirect('socialaccount_login', 'facebook')

BaiTapLonNhom8/register/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render

def get_register(request):
    message = None
    
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # Tạo thông báo thành công
            message = "Tài khoản đã được đăng ký thành công!"
        else:
            # Lấy danh sách các lỗi từ form
            message = "Đã có lỗi xảy ra:"
            for field, errors in form.errors.items():
                for error in errors:
                    message += f"\n- {field}: {error}"
    else:
        form = UserCreationForm()

    return render(request, 'register.html', {'form': form, 'message': message})

BaiTapLonNhom8/templates/baseTemplate.html
<!DOCTYPE html>
<html lang="en">
<head>
<title>Bloscot Blog</title>
      <!-- basic -->
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <!-- mobile metas -->
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="viewport" content="initial-scale=1, maximum-scale=1">
      <!-- site metas -->
      <title>Bloscot</title>
      <meta name="keywords" content="">
      <meta name="description" content="">
      <meta name="author" content="">
      {% load static%}
      <!-- bootstrap css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
      <!-- style css -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
      <!-- Responsive-->
      <link rel="stylesheet" type="text/css" href="{% static 'css/responsive.css' %}">
      <!-- fevicon -->
      <link rel="icon" href="{% static 'images/favicon.ico' %}" type="image/gif" />
      <!-- Scrollbar Custom CSS -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/jquery.mCustomScrollbar.min.css' %}">
      <!-- Tweaks for older IEs-->

      <!-- owl stylesheets -->
      <link rel="stylesheet" type="text/css" href="{% static 'css/owl.carousel.min.css' %}">
      <link rel="stylesheet" type="text/css" href="{% static 'css/owl.theme.default.min.css' %}">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.css" media="screen">
      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<body>
    <div class="header_section">
        <div class="container-fluid header_main">
           <nav class="navbar navbar-expand-lg navbar-light bg-light">
              <a class="logo" href="{% url 'home' %}"><img src="{% static 'images/logo.png' %}" alt="icon"></a>
              <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
              </button>
              <div class="collapse navbar-collapse" id="navbarSupportedContent">
                 <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                       <a class="nav-link" href="{% url 'home' %}">Trang Chủ</a>
                    </li>
                    <li class="nav-item">
                       <a class="nav-link" href="{% url 'blog' %}">Tin Tức</a>
                    </li>
                    <li class="nav-item">
                       <a class="nav-link" href="{% url 'contact' %}">Liên Hệ</a>
                    </li>
                    <li class="nav-item">
                     <a class="nav-link" href="{% url 'blog_app' %}">Thành Viên</a>
                    </li>
                    {% if user.is_authenticated %}
                    <!-- Hiển thị nút đăng xuất nếu người dùng đã đăng nhập -->
                    <li class="nav-item">
                     <a class="nav-link" href="{% url 'profile' %}">Hi, {{ user.username }} </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Thoát</a>
                    </li>
                {% else %}
                    <!-- Hiển thị nút đăng nhập và đăng ký nếu người dùng chưa đăng nhập -->
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'login' %}">Đăng Nhập</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Đăng Ký</a>
                    </li>
                {% endif %}
                 </ul>
              </div>
           </nav>
        </div>
     </div>
    </div>

     <div>
        {% block content %}{% endblock %}
     </div>
    <!-- footer section start -->
    <div class="footer_section layout_padding margin_top_90">
        <div class="container">
           <div class="footer_menu">
              <ul>
                 <li><a href="{% url 'home' %}">Trang Chủ</a></li>
                 <li><a href="{% url 'blog' %}">Tin Tức</a></li>
                 <li><a href="{% url 'contact' %}">Liên hệ</a></li>
                 <li><a href="/admin">Quản trị</a></li>
              </ul>
           </div>
           <div class="contact_menu">
              <ul>
                 <li><a href="#"><img src="{% static 'images/call-icon.png' %}" alt="call"></a></li>
                 <li><a href="#">SDT : +84 946783295</a></li>
                 <li><a href="#"><img src="{% static 'images/mail-icon.png' %}" alt="email"></a></li>
                 <li><a href="#">Nhom_8_mnm@gmail.com</a></li>
              </ul>
           </div>
        </div>
     </div>
    </div>

     <!-- Javascript files-->
     <script src="https://www.gstatic.com/dialogflow-console/fast/messenger/bootstrap.js?v=1"></script>
     <df-messenger
       intent="WELCOME"
       chat-title="Bloscot-Blog"
       agent-id="1b929f0b-0c34-47cd-8527-d79ae07206c3"
       language-code="en"
     ></df-messenger>
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'js/jquery-3.0.0.min.js' %}"></script>
    <script src="{% static 'js/plugin.js' %}"></script>
    <!-- sidebar -->
    <script src="{% static 'js/jquery.mCustomScrollbar.concat.min.js' %}"></script>
    <script src="{% static 'js/custom.js' %}"></script>
    <!-- javascript --> 
    <script src="{% static 'js/owl.carousel.js' %}"></script>
    <script src="https:cdnjs.cloudflare.com/ajax/libs/fancybox/2.1.5/jquery.fancybox.min.js"></script>
    <script src="{% static 'js/ckeditor/ckeditor.js' %}"></script>
    <script>
      CKEDITOR.replace('id_detail');
  </script>
  <script>
   var previousPageUrl = window.location.href;
   var url = 'https://chart.googleapis.com/chart?cht=qr&chs=300x300&chl=' + encodeURIComponent(previousPageUrl);
   document.getElementById("qrcode").src = url;
  </script>
</body>
</html>

BaiTapLonNhom8/templates/blog.html
{% extends "baseTemplate.html" %}
{% block content %}

<!-- recent section start --> 
<div class="about_section layout_padding">
   <div class="container">
       <!-- Thanh tìm kiếm -->
       <div class="row justify-content-center mb-4"> <!-- Thêm class mb-4 để tạo khoảng cách dưới cho thanh tìm kiếm -->
         <div class="col-lg-6">
             <form method="get" class="d-flex">
                 <input type="text" name="q" class="form-control me-2" placeholder="Tìm kiếm...">
                 <button type="submit" class="btn btn-primary">Tìm kiếm</button>
             </form>
         </div>
     </div>     
       <!-- Danh sách các bài viết -->
       <div class="row justify-content-center">
           {% for blog in blogs %}
           <div class="col-lg-8 col-sm-12 mb-4">
               <div class="card rounded">
                   <div class="card mb-3">
                     <img src="/media/{{ blog.thumnail }}" class="card-img-top" alt="...">
                     <div class="card-body">
                        <a href="{% url 'blog_detail' blog_id=blog.id %}"> <h5 class="card-title">{{ blog.title }}</h5></a>
                       <p class="card-text"><small class="text-muted">Đăng bởi: {{ blog.user.username }}</small></p>
                     </div>
                   </div>
               </div> 
           </div>
           {% endfor %}
       </div>
       <div class="col-lg-6 text-lg-end">
         <a href="{% url 'create_blog' %}" class="btn btn-success">Tạo bài viết</a>
     </div>
   </div>
</div>


{% endblock %}

BaiTapLonNhom8/templates/blog_detail.html
{% extends "baseTemplate.html" %}

{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card mt-5">
                <div class="card-body">
                    <h1 class="card-title text-center">{{ blog.title }}</h1>
                    <p class="text-center">Người đăng: {{ blog.user.username }}</p>
                    <div class="text-center">
                        <img src="/media/{{ blog.thumnail }}" class="img-fluid mb-3" alt="Ảnh minh họa">
                    </div>
                    <div class="card-text">
                        {{ blog.detail | safe }}
                    </div>
                </div>
            </div>
                      <!-- Danh sách bình luận -->
<div class="container mt-4">
    <h2>Danh sách bình luận:</h2>
    <div class="list-group">
        {% for comment in blog.comments.all %}
            <div class="list-group-item list-group-item-action">
                <div class="d-flex w-100 justify-content-between">
                    <h5 class="mb-1"><strong>{{ comment.user.username }}</strong></h5>
                    <small>{{ comment.created_at }}</small>
                </div>
                <p class="mb-1">{{ comment.content }}</p>
            </div>
        {% endfor %}
    </div>
</div>
<div class="card-footer py-3 border-0" style="background-color: #f8f9fa;">
    <form method="post" action="{% url 'add_comment' blog.id %}">
        {% csrf_token %}
        <div class="d-flex flex-start w-100">
                <textarea class="form-control" id="textAreaExample" name="content" rows="4" style="background: #fff;"></textarea>
            </div>
        </div>
        <div class="float-end mt-2 pt-1">
            <button type="submit" class="btn btn-primary btn-sm">Bình luận</button>
            <button type="button" class="btn btn-outline-primary btn-sm">Hủy</button>
        </div>
    </form>
</div>
        </div>
    </div>
</div>

{% endblock %}

BaiTapLonNhom8/templates/blogapp.html
{% extends "baseTemplate.html" %}

{% block content %}
<div class="card rounded">
  <div class="container">
      <h2 class="mb-4">Về chúng tôi - Nhóm G08</h2>
      <div class="row">
          <div class="col-md-6 mb-4">
              <div class="card rounded-0 box-shadow">
                  <div class="card-body">
                      <strong class="d-inline-block mb-2 text-primary">Nguyễn Việt Giang</strong>
                      <h3 class="mb-0">
                          <a class="text-dark" href="#">1910A04</a>
                      </h3>
                  </div>
              </div>
          </div>
          <div class="col-md-6 mb-4">
              <div class="card rounded-0 box-shadow">
                  <div class="card-body">
                      <strong class="d-inline-block mb-2 text-success">Trần Thị Hạ</strong>
                      <h3 class="mb-0">
                          <a class="text-dark" href="#">1910A02</a>
                      </h3>
                  </div>
              </div>
          </div>
      </div>
      <div class="row">
          <div class="col-md-6 mb-4">
              <div class="card rounded-0 box-shadow">
                  <div class="card-body">
                      <strong class="d-inline-block mb-2 text-success">Nguyễn Đình Việt Anh</strong>
                      <h3 class="mb-0">
                          <a class="text-dark" href="#">1910A05</a>
                      </h3>
                  </div>
              </div>
          </div>
          <div class="col-md-6 mb-4">
              <div class="card rounded-0 box-shadow">
                  <div class="card-body">
                      <strong class="d-inline-block mb-2 text-warning">Phạm Thị Thu Hiền</strong>
                      <h3 class="mb-0">
                          <a class="text-dark" href="#">1910A03</a>
                      </h3>
                  </div>
              </div>
          </div>
      </div>
  </div>
</div>

{% endblock %}

BaiTapLonNhom8/templates/confirm_delete_blog.html
{% extends "baseTemplate.html" %} {% block content %}

<h2>Xác nhận xóa bài viết</h2>
<p>Bạn có chắc chắn muốn xóa bài viết "{{ blog.title }}"?</p>
<form method="post">
  {% csrf_token %}
  <button type="submit" class="btn btn-danger">Xác nhận</button>
  <a href="{% url 'profile' %}" class="btn btn-secondary">Hủy</a>
</form>

{% endblock %}

BaiTapLonNhom8/templates/contact.html
{% extends "baseTemplate.html" %}

{% block content %}

<!-- contact section start -->
<div class="contact_section layout_padding">
    <div class="container">
       <div class="row">
          <div class="col-md-6">
             <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                   <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active" style="text-indent: 0; border: none; color: #000; font-size: 18px; text-align: center;">1</li>
                   <li data-target="#carouselExampleIndicators" data-slide-to="1"style="text-indent: 0; border: none; color: #000; font-size: 18px; text-align: center;">2</li>
                   <li data-target="#carouselExampleIndicators" data-slide-to="2"style="text-indent: 0; border: none; color: #000; font-size: 18px; text-align: center;">3</li>
                   <li data-target="#carouselExampleIndicators" data-slide-to="3"style="text-indent: 0; border: none; color: #000; font-size: 18px; text-align: center;">4</li>
                </ol>
                <div class="carousel-inner">
                   <div class="carousel-item active">
                      <div class="contact_img"></div>
                   </div>
                   <div class="carousel-item">
                      <div class="contact_img"></div>
                   </div>
                   <div class="carousel-item">
                      <div class="contact_img"></div>
                   </div>
                   <div class="carousel-item">
                      <div class="contact_img"></div>
                   </div>
                </div>
             </div>
          </div>
          <div class="col-md-6">
            <div class="mail_section">
               <div class="container">
                   {% if message %}
                       <p style="color: red;">{{ message }}</p>
                   {% endif %}
                   <!-- Form -->
                   <form method="post">
                       {% csrf_token %}
                       <div class="form-group">
                           <label for="name">Tên:</label>
                           <input type="text" class="form-control" id="name" name="name" placeholder="Nhập tên của bạn">
                       </div>
                       <div class="form-group">
                           <label for="phone">Số điện thoại:</label>
                           <input type="text" class="form-control" id="phone" name="phone" placeholder="Nhập số điện thoại của bạn">
                       </div>
                       <div class="form-group">
                           <label for="email">Email:</label>
                           <input type="email" class="form-control" id="email" name="email" placeholder="Nhập địa chỉ email của bạn">
                       </div>
                       <div class="form-group">
                           <label for="message">Nội dung:</label>
                           <textarea class="form-control" id="message" name="message" placeholder="Nhập nội dung"></textarea>
                       </div>
                       <button type="submit" class="btn btn-primary">Gửi</button>
                   </form>
               </div>
           </div>
           
          </div>
       </div>
    </div>
 </div>
 <!-- contact section end -->

{% endblock %}

BaiTapLonNhom8/templates/create_blog.html
{% extends "baseTemplate.html" %}

{% block content %}
<div class="card border-dark rounded-3" style="max-width: 1000px; margin: 0 auto;">
    <div class="card-body">
        <h1 class="card-title">Đăng Bài Viết Mới</h1>
        <form method="post" enctype="multipart/form-data" class="row g-3">
            {% csrf_token %}
            <div class="mb-3 col-md-6">
                <label for="id_title" class="form-label">Tiêu đề</label>
                {{ form.title }}
            </div>
            <div class="mb-3 col-md-6">
                <label for="id_thumnail" class="form-label">Ảnh minh họa</label>
                {{ form.thumnail }}
            </div>
            <div class="mb-3 col-12">
                <label for="id_detail" class="form-label">Nội dung</label>
                {{ form.detail }}
            </div>
            <div class="col-12">
                <button type="submit" class="btn btn-primary">Đăng Bài Viết</button>
            </div>
        </form>
    </div>
</div>


{% endblock %}

BaiTapLonNhom8/templates/edit_blog.html
{% extends "baseTemplate.html" %} {% block content %}

<h2>Chỉnh sửa bài viết</h2>
<form method="post" enctype="multipart/form-data">
  {% csrf_token %} {{ form.as_p }}
  <button type="submit" class="btn btn-primary">Lưu</button>
</form>

{% endblock %}

BaiTapLonNhom8/templates/facebookLogin.html
<div class="card rounded">
  <a
    href="{% url 'login_with_facebook' %}"
    class="btn btn-primary btn-block mb-4"
    >Đăng Nhập Bằng Facebook</a
  >
</div>

BaiTapLonNhom8/templates/home.html
{% extends "baseTemplate.html" %}

{% load static%}

{% block content %}

 <!-- banner section start --> 
 <div class="container-fluid">
    <div class="banner_section layout_padding">
       <h1 class="banner_taital">Bloscot <br>Blog</h1>
       <div id="my_slider" class="carousel slide" data-ride="carousel">
          <div class="carousel-inner">
             <div class="carousel-item active">
                <div class="image_main">
                   <div class="container">
                      <img src="{% static 'images/img-1.png' %}" alt="" class="image_1">
                      <div class="contact_bt"><a href="{% url 'contact' %}">Liên Hệ</a></div>
                   </div>
                </div>
             </div>
             <div class="carousel-item">
                <div class="image_main">
                   <div class="container">
                      <img src="{% static 'images/img-2.png' %}" alt="" class="image_1">
                      <div class="contact_bt"><a href="{% url 'login' %}">Đăng Nhập</a></div>
                   </div>
                </div>
             </div>
             <div class="carousel-item">
                <div class="image_main">
                   <div class="container">
                      <img src="{% static 'images/img-3.png' %}" alt="" class="image_1">
                      <div class="contact_bt"><a href="{% url 'register' %}">Đăng Ký</a></div>
                   </div>
                </div>
             </div>
          </div>
          <a class="carousel-control-prev" href="#my_slider" role="button" data-slide="prev">
          <i class="fa fa-angle-left"></i>
          </a>
          <a class="carousel-control-next" href="#my_slider" role="button" data-slide="next">
          <i class="fa fa-angle-right"></i>
          </a>
       </div>
    </div>
 </div>
 <!-- banner section end --> 

{% endblock %}

BaiTapLonNhom8/templates/loading.html
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Loading</title>
    <style>
        body {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 100vh;
            margin: 0;
            overflow: hidden;
            background-color: #f4f4f4; /* Màu nền */
        }
        .loader {
            position: relative;
            width: 100px;
            height: 100px;
        }
        .loader:before {
            content: "";
            position: absolute;
            top: 50%;
            left: 50%;
            width: 80px;
            height: 80px;
            border-radius: 50%;
            border: 6px solid #ccc; /* Màu của vòng tròn */
            border-top-color: #007bff; /* Màu của phần đầu tiên của vòng */
            animation: spin 1.5s linear infinite; /* Áp dụng animation */
        }
        @keyframes spin {
            0% { transform: translate(-50%, -50%) rotate(0deg); } /* Bắt đầu từ góc 0 độ */
            100% { transform: translate(-50%, -50%) rotate(360deg); } /* Quay đến góc 360 độ */
        }
        .logo-container {
            width: 200px;
            height: 200px;
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
        }
        .logo {
            width: 100%;
            height: auto;
        }
    </style>
</head>
<body>
    {% load static %}
    <div class="loader"></div>
    <div class="logo-container">
        <!-- Logo của bạn -->
        <img class="logo" src="{% static 'images/logo.png' %}" alt="logo">
    </div>
    <script>
        setTimeout(function() {
            window.location.href = "home/";
        }, 2000);
    </script>
</body>
</html>